import {
  AdminSubmission,
  AdminUser,
  ActivityLogEntry,
  DashboardStats,
} from "@/lib/admin-types";

export const mockAdminUsers: AdminUser[] = [
  {
    id: "1",
    name: "Adaeze Okonkwo",
    email: "adaeze.okonkwo@nddc.gov.ng",
    role: "super_admin",
    status: "active",
    lastLogin: "2026-01-29T10:30:00",
    createdAt: "2024-06-15T00:00:00",
  },
  {
    id: "2",
    name: "Emeka Nwachukwu",
    email: "emeka.nwachukwu@nddc.gov.ng",
    role: "admin",
    status: "active",
    lastLogin: "2026-01-29T09:15:00",
    createdAt: "2024-08-20T00:00:00",
  },
  {
    id: "3",
    name: "Blessing Adekunle",
    email: "blessing.adekunle@nddc.gov.ng",
    role: "staff",
    status: "active",
    lastLogin: "2026-01-28T16:45:00",
    createdAt: "2025-01-10T00:00:00",
  },
  {
    id: "4",
    name: "Chidi Obi",
    email: "chidi.obi@nddc.gov.ng",
    role: "staff",
    status: "inactive",
    lastLogin: "2026-01-15T14:20:00",
    createdAt: "2024-11-05T00:00:00",
  },
  {
    id: "5",
    name: "Ngozi Eze",
    email: "ngozi.eze@nddc.gov.ng",
    role: "admin",
    status: "active",
    lastLogin: "2026-01-29T08:00:00",
    createdAt: "2024-09-12T00:00:00",
  },
];

export const mockSubmissions: AdminSubmission[] = [
  {
    id: "1",
    trackingId: "NDDC-2026-00847",
    submitterName: "John Okafor",
    submitterEmail: "john.okafor@example.com",
    submitterPhone: "+234 803 456 7890",
    type: "project_proposal",
    subject: "Rural Electrification Project - Bayelsa State",
    description:
      "Proposal for the implementation of a comprehensive rural electrification project covering 15 communities in Bayelsa State. The project aims to provide sustainable electricity access to approximately 25,000 residents through solar-hybrid mini-grid installations. This initiative aligns with the federal government's rural development agenda and will create over 200 local jobs during implementation.",
    status: "in-review",
    priority: "high",
    assignedTo: "Emeka Nwachukwu",
    assignedDepartment: "Projects Directorate",
    submittedAt: "2026-01-29T10:34:00",
    lastUpdated: "2026-01-29T14:15:00",
    attachments: [
      {
        id: "1",
        name: "Project_Proposal_v1.pdf",
        size: "2.4 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-29T10:34:00",
      },
      {
        id: "2",
        name: "Budget_Estimate.xlsx",
        size: "156 KB",
        type: "application/xlsx",
        url: "#",
        uploadedAt: "2026-01-29T10:34:00",
      },
      {
        id: "3",
        name: "Site_Survey_Report.pdf",
        size: "5.2 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-29T10:34:00",
      },
    ],
    internalNotes: [
      {
        id: "1",
        content:
          "Initial review completed. Project appears viable and aligns with Q2 priorities. Forwarding to Projects Directorate for technical assessment.",
        authorId: "2",
        authorName: "Emeka Nwachukwu",
        createdAt: "2026-01-29T14:15:00",
        isPrivate: false,
      },
    ],
    responses: [],
    activityLog: [
      {
        id: "1",
        action: "created",
        description: "Submission received via Connect Hub",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-29T10:34:00",
      },
      {
        id: "2",
        action: "viewed",
        description: "Viewed by Emeka Nwachukwu",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-29T11:20:00",
      },
      {
        id: "3",
        action: "priority_changed",
        description: "Priority changed from Medium to High",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-29T11:22:00",
        metadata: { from: "medium", to: "high" },
      },
      {
        id: "4",
        action: "status_changed",
        description: "Status changed from New to In Review",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-29T11:25:00",
        metadata: { from: "new", to: "in-review" },
      },
      {
        id: "5",
        action: "note_added",
        description: "Internal note added",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-29T14:15:00",
      },
    ],
  },
  {
    id: "2",
    trackingId: "NDDC-2026-00846",
    submitterName: "Mary Bassey",
    submitterEmail: "mary.bassey@waterprojects.ng",
    submitterPhone: "+234 809 123 4567",
    type: "report",
    subject: "Q4 2025 Water Supply Project Progress Report - Akwa Ibom",
    description:
      "Quarterly progress report for the ongoing water supply infrastructure project in Akwa Ibom State. This report covers milestones achieved, challenges encountered, and projected timeline for completion. The project is currently 78% complete.",
    status: "resolved",
    priority: "medium",
    assignedTo: "Adaeze Okonkwo",
    assignedDepartment: "Projects Directorate",
    submittedAt: "2026-01-28T09:15:00",
    lastUpdated: "2026-01-29T08:30:00",
    attachments: [
      {
        id: "4",
        name: "Q4_Progress_Report.pdf",
        size: "5.1 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-28T09:15:00",
      },
      {
        id: "5",
        name: "Site_Photos.zip",
        size: "12.8 MB",
        type: "application/zip",
        url: "#",
        uploadedAt: "2026-01-28T09:15:00",
      },
    ],
    internalNotes: [
      {
        id: "2",
        content:
          "Report reviewed and filed. All milestones on track. Contractor performance satisfactory.",
        authorId: "1",
        authorName: "Adaeze Okonkwo",
        createdAt: "2026-01-29T08:30:00",
        isPrivate: false,
      },
    ],
    responses: [
      {
        id: "1",
        type: "detailed",
        content:
          "Thank you for submitting your Q4 2025 progress report. We have reviewed the documentation and confirm that the project milestones are on track. Please continue to submit monthly updates as required.",
        authorId: "1",
        authorName: "Adaeze Okonkwo",
        sentAt: "2026-01-29T08:35:00",
        sentVia: "email",
      },
    ],
    activityLog: [
      {
        id: "6",
        action: "created",
        description: "Submission received",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-28T09:15:00",
      },
      {
        id: "7",
        action: "viewed",
        description: "Viewed by Adaeze Okonkwo",
        userId: "1",
        userName: "Adaeze Okonkwo",
        timestamp: "2026-01-28T10:00:00",
      },
      {
        id: "8",
        action: "response_sent",
        description: "Detailed response sent via email",
        userId: "1",
        userName: "Adaeze Okonkwo",
        timestamp: "2026-01-29T08:35:00",
      },
      {
        id: "9",
        action: "status_changed",
        description: "Status changed to Resolved",
        userId: "1",
        userName: "Adaeze Okonkwo",
        timestamp: "2026-01-29T08:30:00",
        metadata: { from: "in-review", to: "resolved" },
      },
    ],
  },
  {
    id: "3",
    trackingId: "NDDC-2026-00845",
    submitterName: "Peter Udoh",
    submitterEmail: "peter.udoh@gmail.com",
    submitterPhone: "+234 812 345 6789",
    type: "complaint",
    subject: "Road Construction Quality Concerns - Calabar-Itu Highway",
    description:
      "I am writing to formally lodge a complaint regarding the quality of road construction on the Calabar-Itu Highway. Several sections have developed significant potholes and cracks within just 6 months of completion. This poses serious safety risks to motorists and urgently requires investigation and remedial action.",
    status: "forwarded",
    priority: "urgent",
    assignedTo: "Blessing Adekunle",
    assignedDepartment: "Quality Assurance",
    submittedAt: "2026-01-27T14:22:00",
    lastUpdated: "2026-01-28T10:00:00",
    attachments: [
      {
        id: "6",
        name: "Road_Damage_Photos.pdf",
        size: "8.2 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-27T14:22:00",
      },
      {
        id: "7",
        name: "Location_Map.pdf",
        size: "1.1 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-27T14:22:00",
      },
    ],
    internalNotes: [
      {
        id: "3",
        content:
          "URGENT: This requires immediate attention. Forwarded to QA Unit for site inspection. Also notifying Engineering Services.",
        authorId: "2",
        authorName: "Emeka Nwachukwu",
        createdAt: "2026-01-28T10:00:00",
        isPrivate: false,
      },
    ],
    responses: [
      {
        id: "2",
        type: "holding",
        content:
          "Thank you for bringing this matter to our attention. Your complaint has been received and assigned the highest priority. Our Quality Assurance team will conduct a site inspection within the next 48 hours. We will keep you updated on the progress.",
        authorId: "2",
        authorName: "Emeka Nwachukwu",
        sentAt: "2026-01-28T10:15:00",
        sentVia: "both",
      },
    ],
    activityLog: [
      {
        id: "10",
        action: "created",
        description: "Submission received",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-27T14:22:00",
      },
      {
        id: "11",
        action: "viewed",
        description: "Viewed by Emeka Nwachukwu",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-27T14:45:00",
      },
      {
        id: "12",
        action: "priority_changed",
        description: "Priority changed to Urgent",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-27T15:00:00",
        metadata: { from: "medium", to: "urgent" },
      },
      {
        id: "13",
        action: "response_sent",
        description: "Holding response sent",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-28T10:15:00",
      },
      {
        id: "14",
        action: "forwarded",
        description: "Forwarded to Quality Assurance",
        userId: "2",
        userName: "Emeka Nwachukwu",
        timestamp: "2026-01-28T10:00:00",
        metadata: { department: "Quality Assurance" },
      },
    ],
  },
  {
    id: "4",
    trackingId: "NDDC-2026-00844",
    submitterName: "Grace Eze",
    submitterEmail: "grace.eze@communityhealth.org",
    submitterPhone: "+234 805 678 9012",
    type: "request",
    subject: "Funding Request for Community Health Center - Rivers State",
    description:
      "Request for funding support to complete the community health center project in Bonny LGA, Rivers State. The facility is currently 70% complete and requires additional funding of ₦45,000,000 for equipment procurement and initial staffing.",
    status: "new",
    priority: "medium",
    submittedAt: "2026-01-29T08:45:00",
    lastUpdated: "2026-01-29T08:45:00",
    attachments: [
      {
        id: "8",
        name: "Funding_Request_Letter.pdf",
        size: "890 KB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-29T08:45:00",
      },
      {
        id: "9",
        name: "Project_Budget_Breakdown.xlsx",
        size: "245 KB",
        type: "application/xlsx",
        url: "#",
        uploadedAt: "2026-01-29T08:45:00",
      },
      {
        id: "10",
        name: "Construction_Progress_Photos.zip",
        size: "15.6 MB",
        type: "application/zip",
        url: "#",
        uploadedAt: "2026-01-29T08:45:00",
      },
    ],
    internalNotes: [],
    responses: [],
    activityLog: [
      {
        id: "15",
        action: "created",
        description: "Submission received",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-29T08:45:00",
      },
    ],
  },
  {
    id: "5",
    trackingId: "NDDC-2026-00843",
    submitterName: "Samuel Akpan",
    submitterEmail: "samuel.akpan@skillsdev.com",
    submitterPhone: "+234 708 901 2345",
    type: "project_proposal",
    subject: "Skills Acquisition Center Proposal - Delta State",
    description:
      "Proposal to establish a skills acquisition and vocational training center in Warri, Delta State. The center will provide training in welding, plumbing, electrical installation, and ICT skills to 500 youths annually.",
    status: "new",
    priority: "low",
    submittedAt: "2026-01-29T11:20:00",
    lastUpdated: "2026-01-29T11:20:00",
    attachments: [
      {
        id: "11",
        name: "Skills_Center_Proposal.pdf",
        size: "3.5 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-29T11:20:00",
      },
    ],
    internalNotes: [],
    responses: [],
    activityLog: [
      {
        id: "16",
        action: "created",
        description: "Submission received",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-29T11:20:00",
      },
    ],
  },
  {
    id: "6",
    trackingId: "NDDC-2026-00842",
    submitterName: "Amina Mohammed",
    submitterEmail: "amina.m@deltaedu.gov.ng",
    type: "report",
    subject: "Scholarship Program Annual Report 2025",
    description:
      "Annual report on the NDDC scholarship program for the 2025 academic year, including beneficiary statistics, academic performance data, and recommendations for program improvement.",
    status: "pending",
    priority: "medium",
    assignedTo: "Ngozi Eze",
    assignedDepartment: "Admin & Human Resources",
    submittedAt: "2026-01-26T15:30:00",
    lastUpdated: "2026-01-27T09:00:00",
    attachments: [
      {
        id: "12",
        name: "Scholarship_Annual_Report_2025.pdf",
        size: "4.8 MB",
        type: "application/pdf",
        url: "#",
        uploadedAt: "2026-01-26T15:30:00",
      },
    ],
    internalNotes: [
      {
        id: "4",
        content:
          "Assigned to HR department for review. Awaiting verification of beneficiary data.",
        authorId: "5",
        authorName: "Ngozi Eze",
        createdAt: "2026-01-27T09:00:00",
        isPrivate: true,
      },
    ],
    responses: [],
    activityLog: [
      {
        id: "17",
        action: "created",
        description: "Submission received",
        userId: "system",
        userName: "System",
        timestamp: "2026-01-26T15:30:00",
      },
      {
        id: "18",
        action: "assigned",
        description: "Assigned to Ngozi Eze",
        userId: "1",
        userName: "Adaeze Okonkwo",
        timestamp: "2026-01-27T08:30:00",
      },
      {
        id: "19",
        action: "status_changed",
        description: "Status changed to Pending",
        userId: "5",
        userName: "Ngozi Eze",
        timestamp: "2026-01-27T09:00:00",
      },
    ],
  },
];

export const mockActivityLogs: ActivityLogEntry[] = [
  {
    id: "1",
    action: "status_changed",
    description: "Changed status of NDDC-2026-00847 to In Review",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-29T11:25:00",
  },
  {
    id: "2",
    action: "forwarded",
    description: "Forwarded NDDC-2026-00845 to Quality Assurance",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-28T10:00:00",
  },
  {
    id: "3",
    action: "status_changed",
    description: "Changed status of NDDC-2026-00846 to Resolved",
    userId: "1",
    userName: "Adaeze Okonkwo",
    timestamp: "2026-01-29T08:30:00",
  },
  {
    id: "4",
    action: "note_added",
    description: "Added internal note to NDDC-2026-00847",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-29T14:15:00",
  },
  {
    id: "5",
    action: "viewed",
    description: "Viewed submission NDDC-2026-00844",
    userId: "3",
    userName: "Blessing Adekunle",
    timestamp: "2026-01-29T09:00:00",
  },
  {
    id: "6",
    action: "priority_changed",
    description: "Changed priority of NDDC-2026-00845 to Urgent",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-27T15:00:00",
  },
  {
    id: "7",
    action: "response_sent",
    description: "Sent holding response to NDDC-2026-00845",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-28T10:15:00",
  },
  {
    id: "8",
    action: "response_sent",
    description: "Sent detailed response to NDDC-2026-00846",
    userId: "1",
    userName: "Adaeze Okonkwo",
    timestamp: "2026-01-29T08:35:00",
  },
  {
    id: "9",
    action: "downloaded",
    description: "Downloaded attachments from NDDC-2026-00847",
    userId: "2",
    userName: "Emeka Nwachukwu",
    timestamp: "2026-01-29T11:30:00",
  },
  {
    id: "10",
    action: "assigned",
    description: "Assigned NDDC-2026-00842 to Ngozi Eze",
    userId: "1",
    userName: "Adaeze Okonkwo",
    timestamp: "2026-01-27T08:30:00",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalSubmissions: 847,
  newSubmissions: 12,
  pendingReview: 34,
  resolvedToday: 8,
  avgResponseTime: "18 hrs",
  urgentCount: 3,
};
