const queryKeys = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_MY_SUBMISSIONS: "GET_MY_SUBMISSIONS",
  GET_MY_SUBMISSIONS_STATS: "GET_MY_SUBMISSIONS_STATS",
  GET_SUBMISSION_BY_TRACKING_NUMBER: "GET_SUBMISSION_BY_TRACKING_NUMBER",
};

export default queryKeys;
