const queryKeys = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_TODAY_DASHBOARD_STATISTICS: "GET_TODAY_DASHBOARD_STATISTICS",
  GET_ALL_SUBMISSIONS: "GET_ALL_SUBMISSIONS",
  GET_SUBMISSION_DETAILS_BY_TRACKING_NUMBER:
    "GET_SUBMISSION_DETAILS_BY_TRACKING_NUMBER",
};

export default queryKeys;
