const queryKeys = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_DASHBOARD_STATISTICS: "GET_DASHBOARD_STATISTICS",
  GET_TODAY_DASHBOARD_STATISTICS: "GET_TODAY_DASHBOARD_STATISTICS",
  GET_THIS_WEEK_DASHBOARD_STATISTICS: "GET_THIS_WEEK_DASHBOARD_STATISTICS",
  GET_ALL_SUBMISSIONS: "GET_ALL_SUBMISSIONS",
  GET_SUBMISSION_DETAILS_BY_TRACKING_NUMBER:
    "GET_SUBMISSION_DETAILS_BY_TRACKING_NUMBER",
  GET_SUBMISSION_STATUS_STATS: "GET_SUBMISSION_STATUS_STATS",
  GET_SUBMISSION_RESPONSES: "GET_SUBMISSION_RESPONSES",
};

export default queryKeys;
